version: "3.8"

services:
  talk_with_ai:
    image: naren200/talk_with_ai:v1
    container_name: talk_with_ai
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./src/:/root/ros2_ws/src/
      - ./.ollama/models/:/root/.ollama/models/
      - ./start_in_docker.sh:/root/ros2_ws/src/start_in_docker.sh
    environment:
      - DISPLAY=$DISPLAY
      - AUDIO_GID=${AUDIO_GID}
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia 

