version: "3.8"

services:
  talk_with_ai:
    image: naren200/talk_with_ai:v1
    container_name: talk_with_ai
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./src/:/root/ros2_ws/src/
      - ./.ollama/models/:/root/.ollama/models/
      - ./start_in_docker.sh:/root/ros2_ws/src/start_in_docker.sh
      - /run/user/1000/pulse:/run/user/1000/pulse  # Add PulseAudio socket
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie  # Add PulseAudio cookie
    environment:
      - DISPLAY=$DISPLAY
      - AUDIO_GID=${AUDIO_GID}
      - NVIDIA_VISIBLE_DEVICES=all
      - PULSE_SERVER=unix:/run/user/1000/pulse/native  # Add PulseAudio server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia 

